In [1]:
import numpy as np

a = np.array([[23, 15, 84, 95, 94],
              [1, 2, 3, 4, 5],
              [23, 34, 45, 56, 78]])

print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[23 15 84 95 94]
 [ 1  2  3  4  5]
 [23 34 45 56 78]]
2
(3, 5)
15
