In [1]:
import numpy as np

a = np.array([[23, 75, 34],
              [1, 2, 3],
              [23, 34, 45]])

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.T)
print(np.linalg.inv(a))
print(np.linalg.det(a))

[[23 75 34]
 [ 1  2  3]
 [23 34 45]]
2
(3, 3)
9
[[23  1 23]
 [75  2 34]
 [34  3 45]]
[[-0.01075269 -1.98835125  0.140681  ]
 [ 0.02150538  0.22670251 -0.03136201]
 [-0.01075269  0.84498208 -0.02598566]]
1116.0
